### ISSUE TITLE
Enhancement? User notifiation

### ISSUE THREAD

**Issue by maltejahn** [richiewebgate/volumio-mqtt#18]
Hi,

quite special.. but maybe there is a easy way to implement. Quite a long "why":

I have a external device which communicates with volumio.  
I have a "Server" and multiple "Client" for synchronized music output (using snapcast). More or less this device is just a knob to adjust volume with one push button. I want to press this button to "select" the next device.
Now i want to adjust e.g. the volume of one client using the "external device". Every time i press the button, i would like to inform the user that "Client x" is selected. The best would be a static field on top of the UI, but....

Is there a way to do a user notification triggered by a mqtt message? As I understand a simple message could be possible by using a "Toast Message":https://volumio.github.io/docs/Plugin_System/Toast_Messages.html
But no idea how to integrate this into your plugin.

It cant be that easy as the api doesnt seem to have such a function. And i wasnt succesful by just adding a ToastMessage 

else if (action == "printUserMessage") {
                No Idea whats shol;
            }

**Comment by richiewebgate** [comment]
Hi :) 

volumio-mqtt connects via WebSocket and according to the documentation there is no method in the WebSocket API to send toast messages.

It might be possible by writing an additional plugin which uses the commandRouter as outlined in the toast message page you linked, and then call this plugin via WebSocket with "callMethod" to trigger that plugin.. see "callMethod" in https://volumio.github.io/docs/API/WebSocket_APIs.html

volumio-mqtt is not a plugin, it's just a WebSocket client which can be installed on any machine, even remote, so I don't have plans to implement such a plugin. But if you want to try to write a simple toastmsg plugin, I can add the callMethod handler so you can try to invoke it via volumio-mqtt.

cheers

**Comment by richiewebgate** [comment]
have a look at branch [feature/callMethod](https://github.com/richiewebgate/volumio-mqtt/tree/feature/callMethod) if you want to experiment with callMethod and a custom plugin. As mentioned you need to write a small plugin that invokes "self.commandRouter.pushToastMessage" and put it on the volumio device.

**Comment by maltejahn** [comment]
Hi,

and wow. Minutes after my question you already worked on that.

Now i understand - yep, your project is no plugin...

I just created my "own" plugin using volumio plugin init. And now im trying that the plugin listens to the mqtt adapter (where i am absolutely lost). 

There is the onStart function

```
notifyuser.prototype.onStart = function() {
    var self = this;
	var defer=libQ.defer();

	self.commandRouter.pushToastMessage('success', "Yes", "plugin started");
	// try one
	//self.socket.on('callMethod', function (senduser) { self.commandRouter.pushToastMessage('success', "Yes", "got mqtt payload"); });
	//try two
	self.socket.on('callMethod',  (arg) => {  self.commandRouter.pushToastMessage('success', "Yes", "got mqtt payload");} );
	// Once the Plugin has successfull started resolve the promise
	defer.resolve();

    return defer.promise;
};
```

So here, on a "Start" of the plugin i receive a Message. When enabling the line self.socket... the plugin seems not to be loaded. 

Btw. i have problems to let the adapter listen to e.g. devices/volumio-server/.... When I use "mqtt_devicename": "volumio-server" it works perfectly. Should it work when using "subtopics" (do not know how it is called right)

**Comment by richiewebgate** [comment]
your plugin does not have to listen to mqtt. in order to trigger the toast message in your plugin, the new "callMethod" action added in the feature branch of volumio-mqtt should pass the payload to your plugin to a specified method. see documentation for "endpoint" in the payload, which should contain your plugin name and a method name.

Your plugin triggers a toast msg on startup, that's already a good start! Probably you just need to add a method name which can be invoked by "callMethod" of the WebSocket API and then processes the payload of "callMethod" passed by volumio-mqtt.  So your plugin should probably not have a socket.on("callMethod") but something like notifyuser.prototype.submitMyMessage() and then use "submitMyMessage" in the payload passed to volumio-mqtt "callMethod" as the method name.

Just in case, there's a [template for plugins](https://github.com/volumio/Volumio2/tree/master/app/plugins/music_service/example_plugin).

volumio-mqtt subscribes only to config.mqtt_devicename + "/set/#" and "/get/#". If you want volumio-mqtt to receive other topics as well, you have to add them with an additional line of "mqttClient.subscribe(...). if you want to customize volumio-mqtt with your own topics, maybe replace the subscription to config.mqtt_devicename + set/ and get/ with a general mqtt_devicename+"/#" to just listen to every topic that starts with the device name.

**Comment by maltejahn** [comment]
Hi,

about the subtopic. Probably i have written it not the right way. Or i havent understand your explanation
If I want to move my volumio device to a subtopic, i get messages -> that works. But when i want to send something, it doesnt. I think the reason is that you parse e.g. 
<code> if (arr[1] == "set") </code>
which is a fixed position and doenst take into account subtopics. 
I want to listen to "devices/volumio-server/set/stop" instead of "/volumio-server/set/stop"

I modified it the dirty way
<code> if (arr[1+config.topic_offset] == "set") </code> (and every other arr[x] occurrence

with an additional entry in the config:
<code>"topic_offset":1,</code>

after that long text.. i went back to the original code and modified e.g. "/set/#" to "+/set/#"
But not sure if this does the same or do something I am not aware of...
