### ISSUE TITLE
Is there any aditional rquierement?

### ISSUE THREAD

**Issue by smartandsafe** [richiewebgate/volumio-mqtt#7]
hi:

i run the script with updated values (mqtt and devicename)

i see online in pm2 list

i dont get any answer when send messages to mqtt (ex radio-01/set/stop)

i have a new clean volumio installation, do i need to install some aditional library?

diego

**Comment by richiewebgate** [comment]
Hi diego! 
There are no additional libraries required, besides the two listed in the dependencies of the package.json, which will be installed using npm. 
I assume you have done a "npm update" to fetch the required libs, otherwise the script would not start in PM2. 
What do the logs say? (pm2 logs.. )
Try turning on the debug option in config.js first. 

good luck

**Comment by smartandsafe** [comment]
Thanks a lot

everything is ok now

i just updated npm


diego

**Comment by smartandsafe** [comment]
thanks a lot 

everything is ok now

i just updated npm and works ok now.

diego
